incremental_test:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: TestDB
      schema: dbo
      user: sa
      password: yourStrong_Password
      trust_cert: true
      encrypt: false